# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_unit',
            field=models.CharField(default='', max_length=30, verbose_name='Department Unit'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(default='', max_length=30, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_addr',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_address',
            field=models.CharField(default='', max_length=100, verbose_name='Home address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_num',
            field=models.IntegerField(default='0', verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
