# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181026_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_addr',
            field=models.CharField(default='abc@gmail.com', max_length=100, unique=True, verbose_name='Email address'),
        ),
    ]
