# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_addr',
            field=models.CharField(default='abc@gmail.com', max_length=100, verbose_name='Email address'),
        ),
    ]
