# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.BooleanField(default=False)),
                ('hrAdmin', models.BooleanField(default=False)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Dept')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('hod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Hod')),
                ('super_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Superuser')),
            ],
        ),
    ]
