# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='hrAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
