# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True, verbose_name='employee id')),
                ('comment', models.TextField(default='include comment here')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('leave_status', models.CharField(choices=[('Ap', 'Approved'), ('Pn', 'Pending'), ('Dn', 'Declined')], default='Pn', editable=False, max_length=2, verbose_name='Leave Request Status')),
                ('upload', models.FileField(upload_to='uploads/', verbose_name='Attach Document')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('An', 'Annual leave'), ('Pr', 'Proportionate Leave'), ('Cs', 'Casual Leave'), ('Sk', 'Sick Leave'), ('St', 'Study Leave'), ('Cm', 'Compulsory Examination'), ('Nm', 'Non-compulsory Examination'), ('Md', 'Medical Leave'), ('Sb', 'Sabbatical Leave')], max_length=2, verbose_name='Type of leave')),
            ],
        ),
        migrations.AddField(
            model_name='leave_req',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavemgt.Leave_type'),
        ),
    ]
