# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leavemgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_type',
            old_name='leave_type',
            new_name='leavetype',
        ),
    ]
