# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemgt', '0002_auto_20180920_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_req',
            name='leave_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leavemgt.Leave_type'),
        ),
    ]
