# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemgt', '0003_auto_20180920_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_req',
            name='leave_status',
            field=models.CharField(choices=[('Ap', 'Approved'), ('Pn', 'Pending'), ('Dn', 'Declined')], default='Pn', max_length=2, verbose_name='Leave Request Status'),
        ),
    ]
