# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemgt', '0004_auto_20180920_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_req',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave_req',
            name='leavetype',
            field=models.CharField(choices=[('An', 'Annual leave'), ('Pr', 'Proportionate Leave'), ('Cs', 'Casual Leave'), ('Sk', 'Sick Leave'), ('St', 'Study Leave'), ('Cm', 'Compulsory Examination'), ('Nm', 'Non-compulsory Examination'), ('Md', 'Medical Leave'), ('Sb', 'Sabbatical Leave')], default='An', max_length=2, verbose_name='Type of leave'),
        ),
        migrations.DeleteModel(
            name='Leave_type',
        ),
    ]
