# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leavemgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, verbose_name='Department name')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_leave_hist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('leave_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavemgt.Leave_req')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default=uuid.uuid4, editable=False, max_length=10, unique=True, verbose_name='employee id')),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('f_name', models.TextField(max_length=30, verbose_name='First name')),
                ('l_name', models.TextField(max_length=30, verbose_name='Last name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dept_unit', models.CharField(max_length=30, verbose_name='Department Unit')),
                ('home_addr', models.CharField(max_length=100, verbose_name='Home address')),
                ('designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('phone_num', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('email_add', models.CharField(max_length=100, unique=True, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=50, unique=True, verbose_name='Hod Name')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Hod_approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Dept')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Super_user')),
                ('dept', models.CharField(max_length=20, verbose_name='HR Department')),
            ],
        ),
        migrations.AddField(
            model_name='dept',
            name='hod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Hod'),
        ),
    ]
