# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='f_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='l_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
    ]
