# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-20 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180911_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_comment', models.TextField(verbose_name='hod comment')),
                ('hr_comment', models.TextField(verbose_name='hr comment')),
                ('hod_approved', models.BooleanField(default=False)),
                ('hr_approved', models.BooleanField(default=False)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Dept')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='hod_approved',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='hod_approved',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Hod_approved',
        ),
    ]
