# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180920_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='hod_name',
        ),
    ]
