# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181025_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_add',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email address'),
        ),
    ]
