# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20181027_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email_add',
            new_name='email_addr',
        ),
    ]
